"""Initial migration - create all tables

Revision ID: 1b1ce1995f8f
Revises: 
Create Date: 2025-10-13 19:19:53.648781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b1ce1995f8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event_log',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("aggregate_type IN ('USER','ITEM','AUCTION','BID','ORDER','PAYMENT','SHIPMENT')", name='ck_aggregate_type'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_event_log_aggregate', 'event_log', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('idx_event_log_created', 'event_log', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('addresses',
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('street_line1', sa.String(length=200), nullable=False),
    sa.Column('street_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state_region', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('is_default_shipping', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_index('idx_addresses_user', 'addresses', ['user_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_auth_sessions_expires', 'auth_sessions', ['expires_at'], unique=False)
    op.create_index('idx_auth_sessions_user', 'auth_sessions', ['user_id'], unique=False)
    op.create_table('catalogue_items',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_price_normal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_price_expedited', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_time_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_items_category', 'catalogue_items', ['category_id'], unique=False)
    op.create_index('idx_items_seller', 'catalogue_items', ['seller_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_pwd_reset_user', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('auctions',
    sa.Column('auction_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('auction_type', sa.String(), nullable=False),
    sa.Column('starting_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_increment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('winning_bid_id', sa.UUID(), nullable=True),
    sa.Column('winning_bidder_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("auction_type IN ('FORWARD')", name='ck_auction_type'),
    sa.CheckConstraint("status IN ('SCHEDULED','ACTIVE','ENDED','CANCELLED')", name='ck_auction_status'),
    sa.CheckConstraint('end_time > start_time', name='ck_auction_times'),
    sa.ForeignKeyConstraint(['item_id'], ['catalogue_items.item_id'], ),
    sa.ForeignKeyConstraint(['winning_bidder_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('auction_id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index('idx_auctions_status_end', 'auctions', ['status', 'end_time'], unique=False)
    op.create_table('item_images',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['catalogue_items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id'),
    sa.UniqueConstraint('item_id', 'position', name='uq_item_position')
    )
    op.create_table('bids',
    sa.Column('bid_id', sa.UUID(), nullable=False),
    sa.Column('auction_id', sa.UUID(), nullable=False),
    sa.Column('bidder_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.auction_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bidder_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('bid_id')
    )
    op.create_index('idx_bids_auction_amount', 'bids', ['auction_id', 'amount'], unique=False)
    op.create_index('idx_bids_auction_time', 'bids', ['auction_id', 'placed_at'], unique=False)
    op.create_index('idx_bids_bidder', 'bids', ['bidder_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('auction_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('winning_bid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_method', sa.String(), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_address_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("shipping_method IN ('NORMAL','EXPEDITED')", name='ck_shipping_method'),
    sa.CheckConstraint("status IN ('PENDING_PAYMENT','PAID','FAILED','CANCELLED','REFUNDED')", name='ck_order_status'),
    sa.CheckConstraint('total_amount = winning_bid_amount + shipping_cost', name='ck_total_amount'),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.auction_id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['catalogue_items.item_id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['addresses.address_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('auction_id')
    )
    op.create_index('idx_orders_buyer', 'orders', ['buyer_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('processor', sa.String(), nullable=False),
    sa.Column('processor_txn_id', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('INITIATED','AUTHORIZED','CAPTURED','FAILED','REFUNDED')", name='ck_payment_status'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('receipts',
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('receipt_number', sa.String(length=40), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('receipt_id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('estimated_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','PROCESSING','SHIPPED','DELIVERED','CANCELLED')", name='ck_shipment_status'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('shipment_id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    op.drop_table('receipts')
    op.drop_table('payments')
    op.drop_index('idx_orders_buyer', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_bids_bidder', table_name='bids')
    op.drop_index('idx_bids_auction_time', table_name='bids')
    op.drop_index('idx_bids_auction_amount', table_name='bids')
    op.drop_table('bids')
    op.drop_table('item_images')
    op.drop_index('idx_auctions_status_end', table_name='auctions')
    op.drop_table('auctions')
    op.drop_index('idx_pwd_reset_user', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('idx_items_seller', table_name='catalogue_items')
    op.drop_index('idx_items_category', table_name='catalogue_items')
    op.drop_table('catalogue_items')
    op.drop_index('idx_auth_sessions_user', table_name='auth_sessions')
    op.drop_index('idx_auth_sessions_expires', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('idx_addresses_user', table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_index('idx_event_log_created', table_name='event_log')
    op.drop_index('idx_event_log_aggregate', table_name='event_log')
    op.drop_table('event_log')
    op.drop_table('categories')
    # ### end Alembic commands ###
