"""add_phone_to_addresses

Revision ID: 75b032319f67
Revises: 1b1ce1995f8f
Create Date: 2025-11-02 16:41:54.701847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b032319f67'
down_revision: Union[str, None] = '1b1ce1995f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'phone')
    # ### end Alembic commands ###
